### ISSUE TITLE
FahrplanMisc java.lang.NullPointerException

### ISSUE THREAD

**Issue by ITanCh** [tuxmobil/CampFahrplan#167]
```
// CRASH: nerd.tuxmobil.fahrplan.camp (pid 3879)
// Short Msg: java.lang.NullPointerException
// Long Msg: java.lang.NullPointerException: Attempt to read from field 'long nerd.tuxmobil.fahrplan.congress.Lecture.dateUTC' on a null object reference
// Build Label: Android/aosp_flo/flo:6.0.1/MOB30P/tianchi10041651:userdebug/test-keys
// Build Changelist: eng.tianchi.20161004.165046
// Build Time: 1475571199000
// java.lang.NullPointerException: Attempt to read from field 'long nerd.tuxmobil.fahrplan.congress.Lecture.dateUTC' on a null object reference
//  at nerd.tuxmobil.fahrplan.congress.FahrplanMisc.addAlarm(FahrplanMisc.java:280)
//  at nerd.tuxmobil.fahrplan.congress.EventDetailFragment.onAlarmTimesIndexPicked(EventDetailFragment.java:278)
//  at nerd.tuxmobil.fahrplan.congress.EventDetailFragment.onActivityResult(EventDetailFragment.java:265)
//  at nerd.tuxmobil.fahrplan.congress.AlarmTimePickerFragment.passBackAlarmTimesIndex(AlarmTimePickerFragment.java:74)
//  at nerd.tuxmobil.fahrplan.congress.AlarmTimePickerFragment.access$000(AlarmTimePickerFragment.java:18)
//  at nerd.tuxmobil.fahrplan.congress.AlarmTimePickerFragment$1.onClick(AlarmTimePickerFragment.java:49)
//  at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:153)
//  at android.os.Handler.dispatchMessage(Handler.java:102)
//  at android.os.Looper.loop(Looper.java:148)
//  at android.app.ActivityThread.main(ActivityThread.java:5417)
//  at java.lang.reflect.Method.invoke(Native Method)
//  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
//  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
//  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
//
```

I find this problem in my Nexus 7 with Android 6.0.1. My app version is 1.32.0.

**Comment by johnjohndoe** [comment]
This might be fixed in #163 (not merged yet). I would have to check with a bit more time to know for sure.
@ITanCh Can you reproduce the crash? If so, please provide the steps to reproduce the error.
