### ISSUE TITLE
NullPointerException when schedule cannot be fetched

### ISSUE THREAD

**Issue by johnjohndoe** [tuxmobil/CampFahrplan#74]
Given fetching the schedule was not successful. Then you can produce a NPE by tapping on the action "Schedule changes".

```java
E  java.lang.RuntimeException: Unable to start activity 
   ComponentInfo{nerd.tuxmobil.fahrplan.congress/
   nerd.tuxmobil.fahrplan.congress.ChangeListActivity}: java.lang.NullPointerException
E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
E      at android.app.ActivityThread.access$800(ActivityThread.java:139)
E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
E      at android.os.Handler.dispatchMessage(Handler.java:102)
E      at android.os.Looper.loop(Looper.java:136)
E      at android.app.ActivityThread.main(ActivityThread.java:5086)
E      at java.lang.reflect.Method.invokeNative(Native Method)
E      at java.lang.reflect.Method.invoke(Method.java:515)
E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E      at dalvik.system.NativeStart.main(Native Method)
E  Caused by: java.lang.NullPointerException
E      at nerd.tuxmobil.fahrplan.congress.LectureChangesArrayAdapter.initMapper(LectureChangesArrayAdapter.java:261)
E      at nerd.tuxmobil.fahrplan.congress.LectureChangesArrayAdapter.<init>(LectureChangesArrayAdapter.java:35)
E      at nerd.tuxmobil.fahrplan.congress.ChangeListFragment.onCreate(ChangeListFragment.java:69)
E      at android.support.v4.app.Fragment.performCreate(Fragment.java:1763)
E      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:913)
E      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
E      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
E      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
E      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:548)
E      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1194)
E      at android.app.Activity.performStart(Activity.java:5258)
E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2171)
E      ... 11 more
```

 The null pointer is caused in [FahrplanMisc.readChanges](https://github.com/tuxmobil/CampFahrplan/blob/2b91fa87cd10e28869a257ec92084e82ea1429c7/app/src/main/java/nerd/tuxmobil/fahrplan/congress/FahrplanMisc.java#L641)

**Comment by tuxmobil** [comment]
Fixed in 679aad5fc063fa548c7a4fbb462fc16554aefd85
